export const LANG_RU_NAME = 'ru';

export const LANG_RU_TRANS = {
    'USER_TITLE': 'Пользователь',
    'NAME_TITLE': 'Имя',
    'SURNAME_TITLE': 'Фамилия',
    'EMAIL_TITLE': 'Email',
    'PASSWORD_TITLE': 'Пароль',
    'BIRTHDAY_TITLE': 'Дата рождения',
    'LEAGUE_TITLE': 'Лига',
    'REGISTRATION_TITLE': 'Регистрация',
    'AUTHORIZATION_TITLE': 'Авторизация',
    'EXIT_TITLE': 'Выйти',
    'USERS_TITLE': 'Пользователи',
    'LEAGUES_TITLE': 'Лиги',
    'COMPETITIONS_TITLE': 'Соревнования',
    'PROFILE_TITLE': 'Профиль',
    'PHONE_TITLE': 'Телефон',    
    'CITY_TITLE': 'Город',
    'ID_TITLE': 'Id',
    'TITLE_TITLE': 'Название',
    'MAINLEAGUE_TITLE': 'Основная лига',    
    'DESCRIPTION_TITLE': 'Описание',
    'DELETE_BUTTON_TITLE': 'Удалить',
    'EDIT_BUTTON_TITLE': 'Редактировать',
    'SAVE_BUTTON_TITLE': 'Сохранить',
    'RESET_BUTTON_TITLE': 'Сбросить',
    'TYPE_TITLE': 'Тип',
    'DATE_TITLE': 'Дата',
    'LOCATION_TITLE': 'Локация',
    'EDUCATION_TITLE': 'Образование',
    'HEIGHT_TITLE': 'Рост',
    'WEIGHT_TITLE': 'Вес',
    'HISTORY_TITLE': 'История',
    'CHANGES_TITLE': 'Изменения',
    'SET_ADMIN_TITLE': 'Назначить админом',
    'SET_STUDENT_TITLE': 'Назначить студентом',

    'ERROR_NAME_REQUIRED': 'Необходимо ввести имя',
    'ERROR_SURNAME_REQUIRED': 'Необходимо ввести фамилию',
    'ERROR_EMAIL_REQUIRED': 'Необходимо ввести email',
    'ERROR_PASSWORD_REQUIRED': 'Необходимо ввести пароль',
    'ERROR_BIRTHDAY_REQUIRED': 'Необходимо ввести дату рождения',
    'ERROR_TITLE_REQUIRED': 'Необходимо ввести название',

    'ERROR_SELECT_LEAGUE': 'Необходимо указать лигу'
};