export const LANG_UK_NAME = 'uk';

export const LANG_UK_TRANS = {
    'USER_TITLE': 'Користувач',
    'NAME_TITLE': "Ім'я",
    'SURNAME_TITLE': 'Прізвище',
    'EMAIL_TITLE': 'Email',
    'PASSWORD_TITLE': 'Пароль',
    'BIRTHDAY_TITLE': 'Дата народження',
    'LEAGUE_TITLE': 'Ліга',
    'REGISTRATION_TITLE': 'Реєстрація',
    'AUTHORIZATION_TITLE': 'Авторизація',
    'EXIT_TITLE': 'Вийти',
    'USERS_TITLE': 'Користувачі',
    'LEAGUES_TITLE': 'Ліги',
    'COMPETITIONS_TITLE': 'Змагання',
    'PROFILE_TITLE': 'Профіль',
    'PHONE_TITLE': 'Телефон',    
    'CITY_TITLE': 'Місто',
    'ID_TITLE': 'Id',
    'TITLE_TITLE': 'Назва',
    'MAINLEAGUE_TITLE': 'Основна ліга',    
    'DESCRIPTION_TITLE': 'Опис',
    'DELETE_BUTTON_TITLE': 'Видалити',
    'EDIT_BUTTON_TITLE': 'Редагувати',
    'SAVE_BUTTON_TITLE': 'Зберегти',
    'RESET_BUTTON_TITLE': 'Збросити',
    'TYPE_TITLE': 'Тип',
    'DATE_TITLE': 'Дата',
    'LOCATION_TITLE': 'Локація',
    'EDUCATION_TITLE': 'Освіта',
    'HEIGHT_TITLE': 'Зріст',
    'WEIGHT_TITLE': 'Вага',
    'HISTORY_TITLE': 'Історія',
    'CHANGES_TITLE': 'Зміни',
    'SET_ADMIN_TITLE': 'Назначити адміном',
    'SET_STUDENT_TITLE': 'Назначити студентом',

    'ERROR_NAME_REQUIRED': "Необхідно ввести ім'я",
    'ERROR_SURNAME_REQUIRED': 'Необхідно ввести прізвище',
    'ERROR_EMAIL_REQUIRED': 'Необхідно ввести email',
    'ERROR_PASSWORD_REQUIRED': 'Необхідно ввести пароль',
    'ERROR_BIRTHDAY_REQUIRED': 'Необхідно ввести дату народження',
    'ERROR_TITLE_REQUIRED': 'Необхідно ввести назву',

    'ERROR_SELECT_LEAGUE': 'Необхідно вибрати лігу'};